/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Main.FoodMenu;
import Main.FoodOrder;
import Main.IFood;
import Main.IFoodOrder;
import Main.IManager;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huzai
 */
public class FOrders extends javax.swing.JFrame {
IManager manager;

    /**
     * Creates new form FOrderDetails
     */
    public FOrders(IManager manager) {
        this.manager=manager;
        initComponents();
        Load();
    }
public FOrders() {
        initComponents();
        Load();
    }
    void Load()
    {
    IFoodOrder orders = new FoodOrder();
         List<FoodOrder>foodOrders = orders.getAllFoodOrder();
         
           DefaultTableModel tablelist=(DefaultTableModel)jTable1.getModel();
             tablelist.setRowCount(0);
      for(int i=0;i<foodOrders.size();i++)
      { String txt="";
        switch (foodOrders.get(i).getState()) {
            case -1:
                txt="Pending";
                break;
            case 0:
                txt="Rejected";
                break;
            case 1:
                txt="Accepted";
                break;
            default:
                break;
        }
          String data[]={String.valueOf(foodOrders.get(i).getID()),foodOrders.get(i).getCustomer().getName(),txt};
          tablelist.addRow(data);}
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        details1 = new javax.swing.JButton();
        details = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 530));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Orders");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 30, 123, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CName", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 120, 450, 190);

        details1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        details1.setForeground(new java.awt.Color(255, 51, 51));
        details1.setText("Home");
        details1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                details1ActionPerformed(evt);
            }
        });
        getContentPane().add(details1);
        details1.setBounds(0, 0, 150, 31);

        details.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        details.setForeground(new java.awt.Color(255, 51, 51));
        details.setText("View Details");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        getContentPane().add(details);
        details.setBounds(520, 340, 150, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enter ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 340, 110, 30);

        fid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fidActionPerformed(evt);
            }
        });
        getContentPane().add(fid);
        fid.setBounds(310, 330, 190, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ORDERDETAILS.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
        // TODO add your handling code here:\
        IFoodOrder orders = new FoodOrder();
          List<FoodOrder>foodOrders = orders.getAllFoodOrder();
      for(int i=0;i<foodOrders.size();i++)
      {
      if(foodOrders.get(i).getID()==Integer.parseInt(fid.getText()))
      {
          FoodOrder ForItems=foodOrders.get(i);
          this.setVisible(false);
          new FOrderDetails(manager,ForItems).setVisible(true);
      }
      }
        
    }//GEN-LAST:event_detailsActionPerformed

    private void fidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fidActionPerformed

    private void details1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_details1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FoodManagerHome(manager).setVisible(true);
    }//GEN-LAST:event_details1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FOrders().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton details;
    private javax.swing.JButton details1;
    private javax.swing.JTextField fid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
