package Forms;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Forms.*;
import Main.FoodMenu;
import Main.FoodOrder;
import Main.IFood;
import Main.IManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huzai
 */
public class FOrderDetails extends javax.swing.JFrame {
IManager manager;
FoodOrder foodorder;    /**
     * Creates new form FOrderDetails
     */
    public FOrderDetails() {
        initComponents();
    }
public FOrderDetails(IManager manager,FoodOrder foodorder) {
    this.foodorder=foodorder;
    this.manager=manager;
        initComponents();
        Load();
    }
void Load()
{
IFood itemDetails = new FoodMenu();
DefaultTableModel tablelist=(DefaultTableModel)jTable1.getModel();
       
 for (int j = 0; j < foodorder.getItems().size(); j++) {
               String data[]={String.valueOf(foodorder.getID()),foodorder.getCustomer().getName(),itemDetails.getSpecificFoodItem(foodorder.getItems().get(j)).getName()};
          tablelist.addRow(data);
             }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Reject = new javax.swing.JButton();
        Accept1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 530));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Order Details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 30, 260, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CID", "Item"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 130, 450, 190);

        Reject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reject.setForeground(new java.awt.Color(255, 51, 51));
        Reject.setText("Reject");
        Reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectActionPerformed(evt);
            }
        });
        getContentPane().add(Reject);
        Reject.setBounds(430, 350, 110, 31);

        Accept1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Accept1.setForeground(new java.awt.Color(255, 51, 51));
        Accept1.setText("Accept");
        Accept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accept1ActionPerformed(evt);
            }
        });
        getContentPane().add(Accept1);
        Accept1.setBounds(260, 350, 110, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ORDERDETAILS.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectActionPerformed
        // TODO add your handling code here:
         manager.reject(foodorder.getID());
    JOptionPane.showMessageDialog(null,"FoodOrder Rejected");
    this.setVisible(false);
    new FOrders(manager).setVisible(true);
//    Load();
    }//GEN-LAST:event_RejectActionPerformed

    private void Accept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accept1ActionPerformed
        // TODO add your handling code here:
    manager.accept(foodorder.getID());
    JOptionPane.showMessageDialog(null,"FoodOrder Accepted");
    this.setVisible(false);
    new FOrders(manager).setVisible(true);
//    Load();
    }//GEN-LAST:event_Accept1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FOrderDetails().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept1;
    private javax.swing.JButton Reject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
