package Forms;
import Main.ICustomer;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author huzai
 */
public class Home extends javax.swing.JFrame {

    ICustomer customer;
    
    public Home() {
        initComponents();
    }
    public Home(ICustomer customer)
    {
     this.customer=customer;
   initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        reserveroom = new javax.swing.JButton();
        orderfood = new javax.swing.JButton();
        pstqry = new javax.swing.JButton();
        pstdqry = new javax.swing.JButton();
        pstcmplnt = new javax.swing.JButton();
        pstdcmplnt = new javax.swing.JButton();
        checkbooking = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Hotel Managment System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 86);

        jPanel2.setLayout(null);

        logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout);
        logout.setBounds(240, 400, 210, 53);

        reserveroom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reserveroom.setText("Reserve Room");
        reserveroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveroomActionPerformed(evt);
            }
        });
        jPanel2.add(reserveroom);
        reserveroom.setBounds(460, 140, 170, 40);

        orderfood.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderfood.setText("Order Food");
        orderfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderfoodActionPerformed(evt);
            }
        });
        jPanel2.add(orderfood);
        orderfood.setBounds(60, 160, 220, 53);

        pstqry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pstqry.setText("Post Queries");
        pstqry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pstqryActionPerformed(evt);
            }
        });
        jPanel2.add(pstqry);
        pstqry.setBounds(70, 280, 150, 40);

        pstdqry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pstdqry.setText("Posted Queries");
        pstdqry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pstdqryActionPerformed(evt);
            }
        });
        jPanel2.add(pstdqry);
        pstdqry.setBounds(70, 330, 150, 40);

        pstcmplnt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pstcmplnt.setText("Post Complaint");
        pstcmplnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pstcmplntActionPerformed(evt);
            }
        });
        jPanel2.add(pstcmplnt);
        pstcmplnt.setBounds(460, 280, 170, 40);

        pstdcmplnt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pstdcmplnt.setText("Posted Complaint");
        pstdcmplnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pstdcmplntActionPerformed(evt);
            }
        });
        jPanel2.add(pstdcmplnt);
        pstdcmplnt.setBounds(460, 330, 170, 40);

        checkbooking.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbooking.setText("Check Bookings");
        checkbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbookingActionPerformed(evt);
            }
        });
        jPanel2.add(checkbooking);
        checkbooking.setBounds(460, 190, 170, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotel.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, -50, 700, 550);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 92, 700, 519);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderfoodActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FoodMenu1(customer).setVisible(true);
    }//GEN-LAST:event_orderfoodActionPerformed

    private void reserveroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveroomActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ReservationPage(customer).setVisible(true);
    }//GEN-LAST:event_reserveroomActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void pstqryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pstqryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Post_Query(customer).setVisible(true);
    }//GEN-LAST:event_pstqryActionPerformed

    private void pstdqryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pstdqryActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
          new SentQueries(customer).setVisible(true);
    }//GEN-LAST:event_pstdqryActionPerformed

    private void pstcmplntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pstcmplntActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
        new Complaints(customer).setVisible(true);
    }//GEN-LAST:event_pstcmplntActionPerformed

    private void pstdcmplntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pstdcmplntActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
          new SentComplaints(customer).setVisible(true);
                                 
    }//GEN-LAST:event_pstdcmplntActionPerformed

    private void checkbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbookingActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ReservationStatus(customer).setVisible(true);
    }//GEN-LAST:event_checkbookingActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkbooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton orderfood;
    private javax.swing.JButton pstcmplnt;
    private javax.swing.JButton pstdcmplnt;
    private javax.swing.JButton pstdqry;
    private javax.swing.JButton pstqry;
    private javax.swing.JButton reserveroom;
    // End of variables declaration//GEN-END:variables
}
