/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Main.IJob_Application;
import Main.IManager;
import Main.Job_Application;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huzai
 */
public class JobDecision extends javax.swing.JFrame {
    IManager manager;
    /**
     * Creates new form JobDecision
     */
    public JobDecision() {
        initComponents();
      //  Load();
    }
    public JobDecision(IManager manager) {
        this.manager=manager;
        initComponents();
        Load();
    }
    void Load()
    {
    IJob_Application application=new Job_Application();
    List<Job_Application>jobApplications=application.getJob_Applicationss();
     DefaultTableModel tablelist=(DefaultTableModel)jid.getModel();
     tablelist.setRowCount(0);
     for(int i=0;i<jobApplications.size();i++)
      {      
          String data[]={String.valueOf(jobApplications.get(i).getID()),jobApplications.get(i).getApplicant().getName(),jobApplications.get(i).getPost().getName(),String.valueOf(jobApplications.get(i).getPost().getID()),jobApplications.get(i).getStatus()};
          tablelist.addRow(data);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jid = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        book = new javax.swing.JButton();
        book1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logout2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 500));
        getContentPane().setLayout(null);

        jid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Applicant", "Post", "PostID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jid);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 130, 410, 150);

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        jLabel3.setText("Enter ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 310, 90, 40);
        getContentPane().add(Id);
        Id.setBounds(370, 310, 150, 40);

        book.setText("Reject");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        getContentPane().add(book);
        book.setBounds(550, 340, 70, 20);

        book1.setText("Accept");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        getContentPane().add(book1);
        book1.setBounds(550, 300, 70, 20);

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Job Decision");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 40, 220, 44);

        logout2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout2.setText("Home");
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        getContentPane().add(logout2);
        logout2.setBounds(20, 420, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Employment.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-70, -40, 890, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
     int ID=Integer.parseInt(Id.getText());
        manager.accept(ID);
        JOptionPane.showMessageDialog(null,"Rejected");
        Load();  
    }//GEN-LAST:event_bookActionPerformed

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
        int ID=Integer.parseInt(Id.getText());
        manager.accept(ID);
        JOptionPane.showMessageDialog(null,"Accepted");
        Load();
    }//GEN-LAST:event_book1ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StaffManagerHome(manager).setVisible(true);
    }//GEN-LAST:event_logout2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JobDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JobDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JobDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JobDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JobDecision().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JButton book;
    private javax.swing.JButton book1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jid;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JButton logout2;
    // End of variables declaration//GEN-END:variables
}
