package Forms;
import Main.Admin;
import Main.Applicant;
import Main.ICustomer;
import javax.swing.JOptionPane;
import Main.Customer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author huzai
 */

import Main.IApplicant;
import Main.IManager;
import Main.Manager;
import Main.IAdmin;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public Login() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unamebox = new javax.swing.JTextField();
        notreg = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Enteruser = new javax.swing.JLabel();
        Enterpswd = new javax.swing.JLabel();
        logindetail = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        adminlogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        userlogin = new javax.swing.JButton();
        managerlogin = new javax.swing.JButton();
        Applicantlgn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(683, 430));
        setSize(new java.awt.Dimension(683, 430));
        getContentPane().setLayout(null);

        unamebox.setToolTipText("");
        unamebox.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        unamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameboxActionPerformed(evt);
            }
        });
        getContentPane().add(unamebox);
        unamebox.setBounds(380, 170, 220, 40);

        notreg.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 12)); // NOI18N
        notreg.setForeground(new java.awt.Color(0, 102, 102));
        notreg.setText("Not registered?");
        getContentPane().add(notreg);
        notreg.setBounds(390, 350, 120, 30);

        jPasswordField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(380, 250, 220, 40);

        Enteruser.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Enteruser.setText("Email");
        getContentPane().add(Enteruser);
        Enteruser.setBounds(380, 130, 110, 50);

        Enterpswd.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Enterpswd.setText("Password");
        getContentPane().add(Enterpswd);
        Enterpswd.setBounds(380, 220, 110, 30);

        logindetail.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 12)); // NOI18N
        logindetail.setForeground(new java.awt.Color(0, 102, 102));
        logindetail.setText("Login by entering Email Address and Password.  ");
        getContentPane().add(logindetail);
        logindetail.setBounds(60, 340, 270, 30);

        Login.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        Login.setText("Login");
        getContentPane().add(Login);
        Login.setBounds(130, 310, 130, 30);

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3create.jpg"))); // NOI18N
        getContentPane().add(Image);
        Image.setBounds(20, -40, 340, 470);

        adminlogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        adminlogin.setForeground(new java.awt.Color(0, 102, 255));
        adminlogin.setText("Admin Login");
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        getContentPane().add(adminlogin);
        adminlogin.setBounds(500, 300, 120, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Create an account");
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 353, 140, 30);

        userlogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userlogin.setForeground(new java.awt.Color(0, 102, 255));
        userlogin.setText("User Login");
        userlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userloginActionPerformed(evt);
            }
        });
        jPanel1.add(userlogin);
        userlogin.setBounds(380, 300, 120, 20);

        managerlogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        managerlogin.setForeground(new java.awt.Color(0, 102, 255));
        managerlogin.setText("Manager Login");
        managerlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerloginActionPerformed(evt);
            }
        });
        jPanel1.add(managerlogin);
        managerlogin.setBounds(380, 330, 120, 20);

        Applicantlgn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Applicantlgn.setForeground(new java.awt.Color(0, 102, 255));
        Applicantlgn.setText("Applicant Login");
        Applicantlgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplicantlgnActionPerformed(evt);
            }
        });
        jPanel1.add(Applicantlgn);
        Applicantlgn.setBounds(500, 330, 120, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void unameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameboxActionPerformed

    private void managerloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerloginActionPerformed
        // TODO add your handling code here:
        String email=unamebox.getText();
       String pass=new String(jPasswordField1.getPassword());
        IManager manager = new Manager();
        manager = manager.SignIn(email,pass);
        if(manager==null)
        {JOptionPane.showMessageDialog(null," Invalid");}
        else
        if(manager.getType().equals("Room Manager"))
            {
        JOptionPane.showMessageDialog(null,"Room Manager");
            this.setVisible(false);
                new RoomManagerHome(manager).setVisible(true);
            }
        else
            if(manager.getType().equals("Staff Manager"))
            {
            JOptionPane.showMessageDialog(null,"Staff Manager");
            this.setVisible(false);
            new StaffManagerHome(manager).setVisible(true);
            }
        else
            if(manager.getType().equals("Food Manager"))
            {
            JOptionPane.showMessageDialog(null,"Food Manager");
            this.setVisible(false);
            new FoodManagerHome(manager).setVisible(true);
            }
    }//GEN-LAST:event_managerloginActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       // Create_Account.java;
    //   JOptionPane.showMessageDialog(null,"Failed");
        Create_Account create=new Create_Account();
        create.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1MouseClicked

    private void userloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userloginActionPerformed
       String email=unamebox.getText();
       String pass=new String(jPasswordField1.getPassword());
   
        System.out.println(email);
        System.out.println(pass);
        ICustomer customer = new Customer(email,pass);
        boolean cnfrm=customer.Login();
        if(cnfrm==true)
        {
        Home h = new Home(customer);
        this.setVisible(false);
        h.setVisible(true);
        } 
        else
        {
        JOptionPane.showMessageDialog(null,"Invalid");
        }     
       
      
    }//GEN-LAST:event_userloginActionPerformed

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
        // TODO add your handling code here:
        
        String email=unamebox.getText();
       String pswrd=new String(jPasswordField1.getPassword());
         IAdmin admin=new Admin(email,pswrd);
        System.out.println(admin.Login());
        boolean cnfrm=admin.Login();
        if(cnfrm==true)
        {
            this.setVisible(false);
        new ComplaintsReply(admin).setVisible(true);
        } 
        else
        {
        JOptionPane.showMessageDialog(null,"Invalid");
        }     
//       System_class sys=new System_class();
//       int id=CheckAdminlogin(email,pswrd);
//       if(id==0)
//       JOptionPane.showMessageDialog(null,"Invalid");
//       else
//       {
//       sys.saveCurrentUser(id);
//       this.setVisible(false);
//       new Home().setVisible(true);
//       }
    }//GEN-LAST:event_adminloginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ApplicantlgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplicantlgnActionPerformed
        // TODO add your handling code here:
       String email=unamebox.getText();
       String pass=new String(jPasswordField1.getPassword());
   
        System.out.println(email);
        System.out.println(pass);
        IApplicant applicant = new Applicant(email,pass);
        boolean cnfrm=applicant.Login();
        if(cnfrm==true)
        {
        ApplyForJob h = new ApplyForJob(applicant);
        this.setVisible(false);
        h.setVisible(true);
        } 
        else
        {
        JOptionPane.showMessageDialog(null,"Invalid");
        }     
    }//GEN-LAST:event_ApplicantlgnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Applicantlgn;
    private javax.swing.JLabel Enterpswd;
    private javax.swing.JLabel Enteruser;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Login;
    private javax.swing.JButton adminlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel logindetail;
    private javax.swing.JButton managerlogin;
    private javax.swing.JLabel notreg;
    private javax.swing.JTextField unamebox;
    private javax.swing.JButton userlogin;
    // End of variables declaration//GEN-END:variables
}
