package Forms;

import Main.FoodQuery;
import Main.ICustomer;
import Main.IQuery;
import Main.Query;
import Main.RoomQuery;
import Main.StaffQuery;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author huzai
 */
public class Post_Query extends javax.swing.JFrame {
    ICustomer customer;
    /**
     * Creates new form Post_Query
     */
    public Post_Query() {
        initComponents();
        Load();
    }
    public Post_Query(ICustomer customer)
    {
    this.customer=customer;
    initComponents();
    Load();
    }
    public void Load()
    {
    choice1.add("Room");
    choice1.add("Staff");
    choice1.add("Food");
//    choice1.add("Event");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jScrollPane1 = new javax.swing.JScrollPane();
        query1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 500));
        setPreferredSize(new java.awt.Dimension(680, 500));
        setSize(new java.awt.Dimension(769, 768));
        getContentPane().setLayout(null);

        choice1.setName("");
        getContentPane().add(choice1);
        choice1.setBounds(140, 80, 140, 30);

        query1.setColumns(20);
        query1.setRows(5);
        jScrollPane1.setViewportView(query1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 600, 270);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\l191131\\5th Semester\\Sda Proj\\Project\\src\\Images\\query.JPG")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 20, 90, 50);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 20, 60, 50);

        jLabel3.setText("Select Query Type:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 100, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Post");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(558, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Home)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String type=choice1.getSelectedItem();
        String query=query1.getText();
        
        if("Room".equals(type)){
     
        Query roomQuery=new RoomQuery(query);
        customer.postRoomQuery(roomQuery);
        JOptionPane.showMessageDialog(null,"Room Query Sent");
//        Query q=new RoomQuery();
//        IQuery q1=(IQuery) q;
//       List<RoomQuery>r1=q1.GetAllQueries();
        }else
        if("Staff".equals(type))
        {
        Query staffQuery=new StaffQuery(query);
        customer.poststaffQuery(staffQuery);
        JOptionPane.showMessageDialog(null,"Staff Query Sent");
        }
        else
            if("Food".equals(type))
            {
        Query foodQuery=new FoodQuery(query);
        customer.postfoodQuery(foodQuery);
        JOptionPane.showMessageDialog(null,"Food Query Sent");
            }
        
        

//        System.out.print(type);System.out.print(query);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home(customer).setVisible(true);
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Post_Query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Post_Query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Post_Query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Post_Query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Post_Query().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea query1;
    // End of variables declaration//GEN-END:variables
}
