package Forms;




import Forms.*;
import Main.ICustomer;
import Main.IRoom;
import Main.Room;
import Main.RoomReservationRequest;
import java.sql.ResultSet;
import javax.swing.ListModel;
import java.util.ArrayList; // import the ArrayList class
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hassan
 */
public class ReservationStatus extends javax.swing.JFrame {
    ICustomer customer;
//    List<RoomReservationRequest>RRR;
    /**
     * Creates new form ReservationPage
     */
    public ReservationStatus() {
       initComponents();
     //  LoadData();
    }
    public ReservationStatus(ICustomer customer) {
       this.customer=customer;
       initComponents();
       LoadData();
    }
       private void LoadData()
    {
        List<RoomReservationRequest> RRR = customer.checkRRS();
          DefaultTableModel tablelist=(DefaultTableModel)jTable1.getModel();
      for(int i=0;i<RRR.size();i++)
      {      String txt="";
          if(RRR.get(i).getStatus()==-1)
              txt="Pending";
          else
              if(RRR.get(i).getStatus()==0)
                  txt="Rejected";
          else
                  if(RRR.get(i).getStatus()==1)
                      txt="Accepted";
          String data[]={String.valueOf(RRR.get(i).getRoom().getID()),txt};
          tablelist.addRow(data);}
   

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bcd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(840, 500));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RoomNO", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 170, 450, 160);

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("RESERVATION STATUS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 90, 420, 44);

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 80, 23);

        bcd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HOTE.jpg"))); // NOI18N
        getContentPane().add(bcd);
        bcd.setBounds(0, -50, 990, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home(customer).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//   
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReservationStatus().setVisible(true);
//                
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bcd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
