package Forms;




import Forms.*;
import Main.IManager;
import Main.IRoomReservationRequest;
import Main.RoomReservationRequest;
import java.sql.ResultSet;
import javax.swing.ListModel;
import java.util.ArrayList; // import the ArrayList class
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hassan
 */
public class ReservationDecision extends javax.swing.JFrame {
    IManager manager;
    /**
     * Creates new form ReservationPage
     */
    public ReservationDecision() {
       initComponents();
//        LoadData();
    }
    public ReservationDecision(IManager manager) {
        this.manager=manager;
       initComponents();
       Load();
    }
    void Load()
    {
     
         IRoomReservationRequest Irrr = new RoomReservationRequest();
         List<RoomReservationRequest> rrs = Irrr.getAllReservations();
             DefaultTableModel tablelist=(DefaultTableModel)jTable1.getModel();
             tablelist.setRowCount(0);
      for(int i=0;i<rrs.size();i++)
      {  String txt="";
             switch (rrs.get(i).getStatus()) {
                 case -1:
                     txt="Pending";
                     break;
                 case 0:
                     txt="Rejected";
                     break;
                 case 1:
                     txt="Accepted";
                     break;
                 default:
                     break;
             }
          String data[]={String.valueOf(rrs.get(i).getID()),String.valueOf(rrs.get(i).getRoom().getID()),String.valueOf(rrs.get(i).getCustomer().getID()),rrs.get(i).getCustomer().getName(),txt};
          tablelist.addRow(data);}
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accept = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        reject = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bcd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        accept.setText("Accept");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });
        getContentPane().add(accept);
        accept.setBounds(600, 380, 70, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Room", "CID", "CName", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Room");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 210, 450, 160);

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("ROOM DECISION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 120, 300, 44);

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 380, 90, 40);
        getContentPane().add(roomno);
        roomno.setBounds(420, 380, 150, 40);

        reject.setText("Reject");
        reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectActionPerformed(evt);
            }
        });
        getContentPane().add(reject);
        reject.setBounds(600, 410, 70, 23);

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 80, 23);

        bcd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reservation-background-image.jpg"))); // NOI18N
        bcd.setText("jLabel2");
        getContentPane().add(bcd);
        bcd.setBounds(0, 1, 990, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
    int id=Integer.parseInt(roomno.getText());;
    manager.accept(id);
    JOptionPane.showMessageDialog(null,"Reservation Accepted");
    Load();
    }//GEN-LAST:event_acceptActionPerformed

    private void rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectActionPerformed
        // TODO add your handling code here
   int id=Integer.parseInt(roomno.getText());
    manager.reject(id);
    JOptionPane.showMessageDialog(null,"Reservation Rejected    ");
    Load();
    }//GEN-LAST:event_rejectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RoomManagerHome(manager).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//   
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReservationDecision().setVisible(true);
//                
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JLabel bcd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton reject;
    private javax.swing.JTextField roomno;
    // End of variables declaration//GEN-END:variables
}
